Update Run_the_model.R
This is the lasted update before i leave the office

I just expanded the pinit=dunif(0, 200) due to the count data are contained from 0 - around 150 

I still experience the same error following below

Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: RUNTIME ERROR:
Compilation error on line 106.
Attempt to redefine node br[1]