Green Peafowl Population Integrate-Model-0.02
Hi @DrMattG  thank for take a look this model 

I have update some value in the model due to my mistaken previously, however I would like to hear from your that will be better to develop the model forward.

when I have tried to run the whole model in R program with Jags, this is the error shown to me (I ran by using txt thus the line 79 is the line after last }

Error in jags.model(file = "modelgp.txt", data, n.chains = 3, n.adapt = 2000) : 
  
Error parsing model file:
syntax error on line 79 near ""


While I also preparing the model in Nimble and also tried to run the model in R program, when I reach the MCMC the error shown

defining model...
Error: There are multiple definitions for node(s): br[2],br[3],ju[2]..................................................


Another context in the model is  about this code in model

That I saw the researchers using gamma to allocate chick sex, I'm confused that should I used gamma or just used minor 2 due to sex ratio is closed to 50:50

# Allocate chicks to sex (pick only female)
ch[t] ~ dbin(gamma, F[t]) # or just (F[t]/2)

This context I have presented to Tommaso and Niti already but they (as well as me) still not sure for this case thus this would be nice to hear from your.

Best Regard
Ghan Saridnirun